# Generated by Django 5.1.4 on 2024-12-08 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_customer_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='unit_price',
            new_name='price',
        ),
    ]
